config/routes.rb
Curio::Application.routes.draw do
  devise_for :admins
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root to: 'products#index'
  resources :products

  post '/tipsa', to: 'contacts#create'
  get '/tipsa', to: 'contacts#new'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :products
  
  validates_presence_of :name, :address, :latitude, :longitude
  
  geocoded_by :address
  after_validation :geocode 
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :company
  
  validates_presence_of :name, :company, :blurb, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    redirect_to root_url, status: 303
  end
end

app/controllers/contacts_controller.rb
#!/bin/env ruby
# encoding: utf-8
class ContactsController < ApplicationController

  def new
    @message = String.new
  end

  def create
    @message= (params[:message])
    if !@message.blank?
      ContactMailer.contact_msg(@message).deliver
      redirect_to(root_url, :notice => "Tack så mycket! Ditt meddelande har skickats.")
    else
      flash[:error] = "Var snäll och skriv i alla fälten."
      render :new
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :blurb, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def twitterized_type(type)
    case type
      when :alert
        "warning"
      when :danger
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
    end
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/new.html.erb
<% content_for :page_id do %>tipsa_page<% end %>

<div class="row">
	<div class ="col-md-8 col-md-offset-2 paper">
		<h2>Tipsa oss</h2>
		<p>Gärna berätta för oss om du känner till någon unik shopping, upplevelser eller mat i Växjö.</p>
		
		<%= form_tag tipsa_path, method: :post do %>
		  <%= text_area_tag "message", @message, placeholder:"Skriv ditt meddelande här" %>
		  <%= submit_tag "" %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curio</title>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Amatic+SC' rel='stylesheet' type='text/css'>
  
  <%= csrf_meta_tags %>
</head>
<body id="<%= yield :page_id %>">
	
<% flash.each do |type, message| %>
  <div class="alert alert-<%= twitterized_type(type) %>"><button type="button" class="close" >x</button><p><%= message %></p></div>
<% end %>

<div id="page" class="container">
<%= yield %>

</div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br>
    <%= f.text_area :blurb %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="posts" class="row">

 <div class="item corner-stamp">
	<img class="" src="/img/about.jpg" id="about_img">
 </div>

	
  <% @products.each do |product| %>
    <div id="<%= product.id %>" class="item">
        <div class="well">
          <%= link_to product do %>
          	<img class="img-responsive" src="/img/post_img/<%= product.id %>.jpg">
          <% end %>
          <div class="info">
            <h2><%= link_to product.name, product, :data => { :hover => product.name } %></h2>
        	<%= product.blurb %>
          </div>
        </div>
    </div>
   <% end %> 
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% content_for :page_id do %>product_show_page<% end %>

<div class="row">
  <div class ="col-md-8 col-md-offset-2 paper">
  	<div id="back_home">
  		<%= link_to root_url do %>
  		<img id="about_img" class="" src="/img/arrow.png" height="32px" width="43px"> Tillbaka till Hem
  		<% end %>
  	</div>
	Image
	<p>
	  <h2><%= @product.name %></h2>
	  <div class="pa">på</div>
	  <h3> <%= @product.company.name %></h3>
	  <div class="row" id="share-buttons">
	  	  <div class="share-button"><a href="http://www.facebook.com/sharer.php?u=<%= request.original_url %>&t=<%= @product.name %> på <%= @product.company.name %>" class="socialite facebook-share" data-href="<%= request.original_url %>" data-send="true" data-layout="box" data-type="button" data-width="60" data-show-faces="false" rel="external nofollow"><span class="hidden">Share on Facebook</span></a></div>
		  <div class="share-button"><a href="http://twitter.com/share" class="socialite twitter-share" data-text="<%= @product.name %> på <%= @product.company.name %>" data-url="" data-count="none" rel="nofollow" target="_blank"><span class="vhidden">Share on Twitter</span></a></div>
		  <div class="share-button"><a href="//www.pinterest.com/pin/create/button/" class="socialite pinterest-pinit" data-pin-do="buttonBookmark"  data-pin-color="red" ><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_red_28.png" /></a></div>
	  </div>
	</p>
	
	<p>
	  <%= @product.description %>
	</p>
	
	<p>
	  <%= @product.company.name %><br>
	  <%= @product.company.address %>
	  <marker latitude="<%= @product.company.latitude %>" longitude="<%= @product.company.longitude %>"></marker>
	  <div id="map_canvas"></div>
	</p>
  </div>
</div>